name: Build on Commit

on:
  push:
    branches:
      - actions

jobs:
  build:
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v4
    
      - name: Install Pester
        run: pwsh -Command "Install-Module -Name Pester -Force"
      - name: Run Pester
        run: pwsh -Command "Invoke-Pester -Path .\XlsCoordinatesConverter.Tests.ps1"

      - name: Install PSScriptAnalyser
        run: pwsh -Command "Install-Module -Name PSScriptAnalyzer -Force"
      - name: Run PSScriptAnalyser
        run: pwsh -Command "Invoke-ScriptAnalyzer -File .\XlsCoordinatesConverter.ps1"

# jobs:
#   build:
#     runs-on: [self-hosted, linux]

#     steps:
#       - uses: actions/checkout@v4

#       - name: Install Invoke-Build
#         run: pwsh -Command "Install-Module -Name InvokeBuild -Force"

#       - name: Install PSScriptAnalyser
#         run: pwsh -Command "Install-Module -Name PSScriptAnalyzer -Force"

#       - name: Install Pester
#         run: pwsh -Command "Install-Module -Name Pester -Force"

#       - name: Run build script
#         run: pwsh -Command "Invoke-Build ."