name: Build on Commit

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Invoke-Build
        run: pwsh -Command "Install-Module -Name InvokeBuild -Force"

      - name: Run build script
        run: pwsh -Command "Invoke-Build ."