name: Build on Commit

on: [push]

jobs:
  build:
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install Invoke-Build
        run: pwsh -Command "Install-Module -Name InvokeBuild -Force"

      - name: Install PSScriptAnalyser
        run: pwsh -Command "Install-Module -Name PSScriptAnalyzer -Force"

      - name: Install Pester
        run: pwsh -Command "Install-Module -Name Pester -Force"

      - name: Run build script
        run: pwsh -Command "Invoke-Build ."